### ISSUE TITLE
Ругается на отсутсвие ColorImages

### ISSUE THREAD

**Issue by Terxeno** [HemulGM/Weather#1]
Ругается на отсутствие функции ColorImages(ImageList24, i, AColor);
132 строчка
```
procedure TFormWeather.SetThemeColor(AColor: TColor);
var
  i: Integer;
begin
  for i := 0 to ImageList24.Count - 1 do
    ColorImages(ImageList24, i, AColor);
  SetFontColor(AColor);
end;
```

**Comment by HemulGM** [comment]
Если скачал уже HGM Components, то эта ты функция просто переехала в модуль HGM.Common.PngUtils

**Comment by Terxeno** [comment]
Добавил модуль, но теперь он ругается на **PNGImageList**, я так понимаю это из **TurboPack PNGComponents**?

**Comment by HemulGM** [comment]
Это как раз причина, по которой я перенес метод в другой модуль. Это отдельная зависимость. Не обязательная для работы самих компонентов в пакете.
Пакет PngImageList можно взять из GetIt или из TurboPack, да
